project_id = "daqulcthlnmmydhiuvsz"

[functions.analyze-trade]
verify_jwt = false

[functions.deposit-notification]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.verify-bank-account]
verify_jwt = false

[functions.trading-mentor]
verify_jwt = false

[functions.validate-receipt]
verify_jwt = false

[functions.daily-notifications]
verify_jwt = false

[functions.resolve-coin-flip]
verify_jwt = false

[functions.resolve-jackpot]
verify_jwt = false

[functions.notify-activity]
verify_jwt = false
